### ISSUE TITLE
Govalid with Pointer Types is not possible

### ISSUE THREAD

**Issue by Dominik-Robert** [twharmon/govalid#32]
The govalid struct validation is only for non pointer types. Is there any reason for that? I think there a some great possibilities for pointers with govalid tags. 

Is this already in planning? If not I can try to investigate further and maybe make a pull request

```bash
go version go1.16.2 windows/amd64
```

**Comment by twharmon** [comment]
> The govalid struct validation is only for non pointer types.

What exactly are you referring to here? The `s` argument here can be a pointer: `func (v *Validator) Violation(s interface{}) (string, error)`.

**Comment by Dominik-Robert** [comment]
Sorry for the late response:

```golang
type Test struct {
	Name *string `govalid:"max:10`
}
```

I mean the above code. It will ignored if the Name Field is not 10 characters long, so it doesn´t matter how long the Name field is.

Or you have a code example where field pointer types are supported and actually working?

**Comment by twharmon** [comment]
Thanks for the clarification. Sounds like a good thing to add. Feel free to make a PR for discussion.
